### ISSUE TITLE
train.py :RuntimeError: GroupedGEMM run failed

### ISSUE THREAD

**Issue by LaooBaoo** [SirryChen/CACL#4]
hello  some problems occured when i run train.py:
~/CACL$ python train.py
valid:   0%|                                                                                           | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/bjf/CACL/train.py", line 227, in <module>
    valid(valid_dataset)    # first forward for initializing model
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/bjf/CACL/train.py", line 130, in valid
    _, node_predict = CLModel(subgraph.to(device_cl).detach())
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bjf/CACL/CL_model.py", line 145, in forward
    node_embeddings = self.encoder(graph)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bjf/CACL/CL_model.py", line 101, in forward
    node_embedding = Conv(node_embedding, edge_index)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/conv/hgt_conv.py", line 192, in forward
    k, v, src_offset = self._construct_src_node_feat(
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/conv/hgt_conv.py", line 151, in _construct_src_node_feat
    k = self.k_rel(ks, type_vec).view(H, -1, D).transpose(0, 1)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/dense/linear.py", line 325, in forward
    self._update_timing_cache(x, type_ptr, key)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/dense/linear.py", line 287, in _update_timing_cache
    _ = self.forward_segmm(x, type_ptr)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/dense/linear.py", line 271, in forward_segmm
    return pyg_lib.ops.segment_matmul(x, type_ptr, self.weight)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/pyg_lib/ops/__init__.py", line 169, in segment_matmul
    out = torch.ops.pyg.segment_matmul(inputs, ptr, other)
  File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/_ops.py", line 442, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: GroupedGEMM run failed
valid:   0%|                                                                                           | 0/1 [00:02<?, ?it/s]

it seems like the problem is due to muti-gpu running? 

environment :
torch                    1.13.1
torch-cluster            1.6.1+pt113cu116
torch_geometric          2.5.3
torch-scatter            2.1.1+pt113cu116
torch-sparse             0.6.17+pt113cu116
torchaudio               0.13.1
torchvision              0.14.1
scikit-learn             1.3.0
scipy                    1.12.0
pyg-lib                  0.4.0+pt113cu116
pyg-library              0.2.0

**Comment by LaooBaoo** [comment]
> hello some problems occured when i run train.py: ~/CACL$ python train.py valid: 0%| | 0/1 [00:00<?, ?it/s]Traceback (most recent call last): File "/home/bjf/CACL/train.py", line 227, in valid(valid_dataset) # first forward for initializing model File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/home/bjf/CACL/train.py", line 130, in valid _, node_predict = CLModel(subgraph.to(device_cl).detach()) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/bjf/CACL/CL_model.py", line 145, in forward node_embeddings = self.encoder(graph) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/bjf/CACL/CL_model.py", line 101, in forward node_embedding = Conv(node_embedding, edge_index) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/conv/hgt_conv.py", line 192, in forward k, v, src_offset = self._construct_src_node_feat( File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/conv/hgt_conv.py", line 151, in _construct_src_node_feat k = self.k_rel(ks, type_vec).view(H, -1, D).transpose(0, 1) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/dense/linear.py", line 325, in forward self._update_timing_cache(x, type_ptr, key) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/dense/linear.py", line 287, in _update_timing_cache _ = self.forward_segmm(x, type_ptr) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch_geometric/nn/dense/linear.py", line 271, in forward_segmm return pyg_lib.ops.segment_matmul(x, type_ptr, self.weight) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/pyg_lib/ops/**init**.py", line 169, in segment_matmul out = torch.ops.pyg.segment_matmul(inputs, ptr, other) File "/home/bjf/anaconda3/envs/CACL/lib/python3.10/site-packages/torch/_ops.py", line 442, in **call** return self._op(*args, **kwargs or {}) RuntimeError: GroupedGEMM run failed valid: 0%| | 0/1 [00:02<?, ?it/s]
> 
> it seems like the problem is due to muti-gpu running?
> 
> environment : torch 1.13.1 torch-cluster 1.6.1+pt113cu116 torch_geometric 2.5.3 torch-scatter 2.1.1+pt113cu116 torch-sparse 0.6.17+pt113cu116 torchaudio 0.13.1 torchvision 0.14.1 scikit-learn 1.3.0 scipy 1.12.0 pyg-lib 0.4.0+pt113cu116 pyg-library 0.2.0



I have solved the problem ，it is caused by the broken gpu ， i put code on another gpu and make it！
